在团队开发时，队友推送了分支，而自己恰好也推送（相同的分支），会报异常

error: failed to push some refs to 'git@github.com:michaelliao/learngit.git'

解决方法，先从github获取最新提交，然后抓下来

git branch --set-upstream dev origin/dev	//指定本地和远程库的分支

git pull		//抓取

在本地合并，解决冲突再推送

git status 		//先查看有没有冲突,然后修改冲突

git add xx		

git commit -m"xx"	

git push origin dev	//修改提交完毕直接推送，在pull的时候就已经合并了不过要解决冲突


多人协作的工作模式通常是这样：
首先git clone git@github.com:michaelliao/learngit.git 把库克隆过来

其次git checkout -b dev origin/dev 再把分支克隆过来，远程库和本地新建分支名最好最好一致

推送时，可以试图用git push origin xx推送自己的修改；

如果推送失败，则因为远程分支比你的本地更新，需要先用git pull试图合并；

如果合并有冲突，则解决冲突，并在本地提交；

没有冲突或者解决掉冲突后，再用git push origin xx推送就能成功！

如果git pull提示“no tracking information”，则说明本地分支和远程分支的链接关系没有创建，用命令git branch --set-upstream xx origin/xx

这就是多人协作的工作模式，一旦熟悉了，就非常简单。
